### ISSUE TITLE
Consider a public S3 bucket for Open source artifacts like Lambda   

### ISSUE THREAD

**Issue by glennbech** [telia-oss/terraform-modules#4]
To make adoption of some components in this repository easier, it could be an idea to have a public S3 bucket for artifacts like Lambda distributions. As an example, we could put the S3 Log forwarder lambda zip file in the bucket- and the terraform component would work "out of the box" for users trusting Telia enough to use the artifact provided in the bucket.

**Comment by itsdalmo** [comment]
This work is underway! We are provisioning an new "opensource" AWS account where we can grant Travis access to upload artifacts. Once the account is in place we'll try to figure out a good pattern for uploading releases to S3 and referencing them from the modules, so hopefully all we'll have to do is reference the module and it'll use the version of the artifact (that we have pre-built) that matches the module (by default).

Adding a list of projects that I know are waiting for a solution:
- https://github.com/telia-oss/terraform-modules/tree/master/cloudwatch-logs-s3-forwarder
- https://github.com/telia-oss/concourse-github-lambda
- https://github.com/telia-oss/concourse-sts-lambda
- https://github.com/telia-oss/aws-notify-slack - @mhd999 

PS: For this to work, we'll probably want to put the lambda code and terraform in the same repository.

**Comment by mikael-lindstrom** [comment]
We now have a separate account with a opensource bucket (telia-oss) and everything except [cloudwatch-logs-s3-forwarder](https://github.com/telia-oss/terraform-modules/tree/master/cloudwatch-logs-s3-forwarder) is now available there. Since its configured in an internal repo just ping me or @itsdalmo and we will help you set it up @glennbech.
